### PR TITLE
Fix uninstall

### LINKED ISSUE #26869: Unable to uninstall native module ps_dataprivacy
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Unable to uninstall native module ps_dataprivacy

I have this problem even having version 2.0.1

Prestasop 1.7.7.3
https://www.awesomescreenshot.com/video/6280974?key=3a7c0711685e27352f2c10e0273e8822

Prestasop 1.7.8.0
https://www.awesomescreenshot.com/video/6281019?key=8bd2711d6efa9e2d1c7caabba93e6bdf

### Expected behavior

Be able to uninstall native module ps_dataprivacy

### Steps to reproduce

Go to Module Manager
Click on Uninstall module ps_dataprivacy
See erro

### PrestaShop version(s) where the bug happened

1.7.7.3 - 1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_dataprivacy

### PR DESCRIPTION
**Pull request by alfonsolr09**
https://github.com/PrestaShop/PrestaShop/issues/26869

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | https://github.com/PrestaShop/PrestaShop/issues/26869
| Type?         | bug fix 
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | Fixes PrestaShop/Prestashop#26869
| How to test?  | Try to uninstall or reset.

### CODE REVIEW

**Comment by alfonsolr09** [comment]
i used master, not developer branch

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm sorry but could you please use the dev branch. and also create the upgrade script related to this change?

**Comment by alfonsolr09** [comment]
i cant find this code on dev branch @PierreRambaud

**Comment by alfonsolr09** [comment]
I don't understand the construction of the module, where is the uninstallation and installation code? do you extract it from the old prestashop 1.6 module?

**Comment by PierreRambaud** [comment]
> i cant find this code on dev branch @PierreRambaud

It's because it's already fixed on the dev branch and the module needs to be released
https://github.com/PrestaShop/ps_dataprivacy/pull/21

**Comment by alfonsolr09** [comment]
release it...

**Comment by PierreRambaud** [comment]
> release it...

Yes, we will do it as soon as possible.

I'm closing your pull request as the fix is already merged on the dev branch.

Thank you

**Pull request closed without merging**
